In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer 


df = pd.read_csv("USvideos_modified.csv", sep=",")
df.head(3)

,video_id,last_trending_date,publish_date,publish_hour,category_id,channel_title,views,likes,dislikes,comment_count,...,tag_appeared_in_title,title,tags,description,trend_day_count,trend.publish.diff,trend_tag_highest,trend_tag_total,tags_count,subscriber
0,2kyS6SvSYSE,2017-11-20,2017-11-13,17,22,CaseyNeistat,2564903,96321,7972,22149,...,False,WE WANT TO TALK ABOUT OUR MARRIAGE,SHANtell martin,SHANTELL'S CHANNEL - https://www.youtube.com/s...,7,7,2,2,1,9086142.0
1,1ZAPwfrtAFY,2017-11-20,2017-11-13,7,24,LastWeekTonight,6109402,151250,11508,19820,...,False,The Trump Presidency: Last Week Tonight with J...,last week tonight trump presidency|last week t...,"One year after the presidential election, John...",7,7,65,69,4,5937292.0
2,5qpjK5DgCt4,2017-11-20,2017-11-12,19,23,Rudy Mancuso,5315471,187303,7278,9990,...,True,"Racist Superman | Rudy Mancuso, King Bach & Le...",racist superman|rudy|mancuso|king|bach|racist|...,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,7,8,68,426,23,4191209.0

In [2]:
#filling in descriptions that were blank
df.description= df.description.fillna('No description provided')
df.tags= df.tags.fillna('')
df = df.dropna() #no information provided for subscribers to we eliminate those rows
df.shape

(4525, 23)

coun_vect = CountVectorizer(stop_words='english',min_df=2) #max_features=3 (gives top 3 or x values)
count_matrix = coun_vect.fit_transform(df['tags'])
count_array = count_matrix.toarray()
df = pd.DataFrame(data=count_array,columns = coun_vect.get_feature_names())
#print(df) #df.shape #df.columns (general infor)
#print(coun_vect.vocabulary_) #with position of word in matrix
#print( coun_vect.get_feature_names()) #without position of word in sparse matrix
print(count_array)

In [3]:
count=CountVectorizer()

count.fit(df['title'])

count.get_feature_names()

count_tranform=count.transform(df['title'])
# Need to convert into Array
cv_array=count_tranform.toarray()
cv_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [4]:
limt_cv_title=CountVectorizer(stop_words='english',max_features=50)
limt_cv_title.fit(df['title'])
cv_transformed_title = limt_cv_title.fit_transform(df['title'])
cv_array_title = cv_transformed_title.toarray()
cv_df_title=pd.DataFrame(cv_array_title,columns=limt_cv_title.get_feature_names()).add_prefix("")
cv_df_title.head()
#for col_name in cv_df_title.columns: 
    #print(col_name)

,10,2017,2018,audio,best,big,black,bowl,challenge,christmas,...,talk,time,trailer,trump,video,vs,wars,week,world,year
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
limt_cv_tags=CountVectorizer(stop_words='english',max_features=50)
limt_cv_tags.fit(df['tags'])
cv_transformed_tags = limt_cv_tags.fit_transform(df['tags'])
cv_array_tags = cv_transformed_tags.toarray()
cv_df_tags=pd.DataFrame(cv_array_tags,columns=limt_cv_tags.get_feature_names()).add_prefix("")
#for col_name in cv_df_tags.columns: 
    #print(col_name)

In [6]:
limt_cv_des=CountVectorizer(stop_words='english',max_features=50)
limt_cv_des.fit(df['description'])
cv_transformed_des = limt_cv_des.fit_transform(df['description'])
cv_array_des = cv_transformed_des.toarray()
cv_df_des=pd.DataFrame(cv_array_des,columns=limt_cv_des.get_feature_names()).add_prefix("")
#for col_name in cv_df_des.columns: 
    #print(col_name)

In [7]:
tv=TfidfVectorizer()

tv.fit(df['title'])

tv_transformed = tv.fit_transform(df['title'])

tv_df = pd.DataFrame(tv_transformed.toarray(), 
                     columns=tv.get_feature_names()).add_prefix("")
tv_df

,000,000fps,000hp,003,01,02,06,09,10,100,...,태연,트롯터,판문점,포니,피카부,한국,한세,했다,회오리젤리,힐링쿠킹
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4520,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4523,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4524,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
tv_tfidf=TfidfVectorizer(max_features=50,stop_words="english")

transform=tv_tfidf.fit_transform(df['title'])

tv_vectorizer_title=pd.DataFrame(transform.toarray(),columns=tv_tfidf.get_feature_names()).add_prefix("")
tv_vectorizer_title

,10,2017,2018,audio,best,big,black,bowl,challenge,christmas,...,talk,time,trailer,trump,video,vs,wars,week,world,year
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.547204,0.0,0.0,0.0,0.59303,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4520,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
4521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
4522,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
4523,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
4524,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0

for col_name in tv_vectorizer_title.columns: 
    print(col_name)

In [9]:
tv_tfidf=TfidfVectorizer(max_features=50,stop_words="english")

transform=tv_tfidf.fit_transform(df['tags'])

tv_vectorizer_tags=pd.DataFrame(transform.toarray(),columns=tv_tfidf.get_feature_names()).add_prefix("")
tv_vectorizer_tags

,2017,2018,beauty,best,black,bowl,cat,celebrity,christmas,comedy,...,talk,trailer,trump,tutorial,tv,video,videos,wars,world,youtube
0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,1.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.000000,0.47424,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.316885,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.337121,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.717141,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4520,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4521,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4522,0.0,0.0,0.0,0.867538,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4523,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4524,0.0,0.0,0.0,0.489057,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

for col_name in tv_vectorizer_tags.columns: 
    print(col_name)

In [10]:
tv_tfidf=TfidfVectorizer(max_features=50,stop_words="english")

transform=tv_tfidf.fit_transform(df['description'])

tv_vectorizer_des=pd.DataFrame(transform.toarray(),columns=tv_tfidf.get_feature_names()).add_prefix("")
tv_vectorizer_des

,amzn,bit,cbs,channel,com,facebook,gl,goo,google,http,...,time,tumblr,twitter,video,videos,watch,world,www,youtu,youtube
0,0.613489,0.000000,0.0,0.052096,0.442198,0.033761,0.000000,0.000000,0.0,0.591912,...,0.000000,0.000000,0.032940,0.093011,0.000000,0.000000,0.000000,0.093102,0.000000,0.039252
1,0.000000,0.000000,0.0,0.177192,0.376009,0.229662,0.000000,0.000000,0.0,0.301988,...,0.000000,0.000000,0.224074,0.000000,0.000000,0.000000,0.000000,0.211109,0.000000,0.267013
2,0.000000,0.000000,0.0,0.055748,0.561918,0.036128,0.000000,0.000000,0.0,0.475052,...,0.000000,0.000000,0.035249,0.049765,0.054905,0.056290,0.000000,0.033209,0.000000,0.630052
3,0.000000,0.101787,0.0,0.000000,0.415635,0.039056,0.079589,0.079487,0.0,0.034237,...,0.000000,0.077121,0.038106,0.053799,0.000000,0.060853,0.000000,0.143605,0.168694,0.136225
4,0.000000,0.000000,0.0,0.119484,0.443713,0.077433,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.075549,0.000000,0.000000,0.000000,0.000000,0.427066,0.000000,0.090026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4520,0.000000,0.000000,0.0,0.000000,0.718618,0.000000,0.000000,0.000000,0.0,0.342016,...,0.000000,0.000000,0.190331,0.000000,0.000000,0.151974,0.000000,0.179319,0.000000,0.113402
4521,0.000000,0.000000,0.0,0.000000,0.529809,0.161801,0.000000,0.000000,0.0,0.141837,...,0.000000,0.000000,0.157864,0.000000,0.000000,0.000000,0.000000,0.446191,0.000000,0.000000
4522,0.000000,0.500759,0.0,0.000000,0.179761,0.054898,0.000000,0.000000,0.0,0.384996,...,0.111304,0.000000,0.107125,0.000000,0.166863,0.000000,0.000000,0.100926,0.000000,0.000000
4523,0.000000,0.000000,0.0,0.000000,0.175062,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.393154,0.000000,0.497265
4524,0.000000,0.000000,0.0,0.097100,0.180293,0.000000,0.064116,0.064034,0.0,0.000000,...,0.000000,0.000000,0.000000,0.130019,0.047816,0.294135,0.122161,0.202450,0.475643,0.256062

for col_name in tv_vectorizer_des.columns: 
    print(col_name)

In [11]:
count_comparison = pd.DataFrame(cv_df_title.columns, columns=['Title'])
count_comparison["Tags"]= cv_df_tags.columns
count_comparison["Description"]= cv_df_des.columns
count_comparison

         Title           Tags Description
0           10           2017        amzn
1         2017           2018         bit
2         2018         beauty         cbs
3        audio           best     channel
4         best          black         com
5          big           bowl    facebook
6        black            cat          gl
7         bowl      celebrity         goo
8    challenge      christmas      google
9    christmas         comedy        http
10  commercial            diy       https
11         day            dog   instagram
12        espn          ellen       jimmy
13          ft  entertainment        late
14        game           food        like
15          hd          funny        list
16  highlights           game        live
17       house      interview        love
18       james         iphone          ly
19        jedi          james        make
20        john           late       music
21        life           life         nbc
22        like           live         new
23        live           make        news
24        look         makeup   nfacebook
25        love          movie         nfl
26        make         movies     nfollow
27      makeup          music        nget
28         man            nbc       nhttp
29       movie            new      nhttps
30       music           news          ni
31     netflix          night       night
32         new       official  ninstagram
33        news            pop       nlike
34         nfl         review  nsubscribe
35    official        science        nthe
36      review         season    ntwitter
37      season             sp      nwatch
38        star           star    smarturl
39       super          super   subscribe
40        talk           talk        time
41        time        trailer      tumblr
42     trailer          trump     twitter
43       trump       tutorial       video
44       video             tv      videos
45          vs          video       watch
46        wars         videos       world
47        week           wars         www
48       world          world       youtu
49        year        youtube     youtube

In [12]:
td_comparison = pd.DataFrame(tv_vectorizer_title.columns, columns=['Title'])
td_comparison["Tags"]= tv_vectorizer_tags.columns
td_comparison["Description"]= tv_vectorizer_des.columns
td_comparison

         Title           Tags Description
0           10           2017        amzn
1         2017           2018         bit
2         2018         beauty         cbs
3        audio           best     channel
4         best          black         com
5          big           bowl    facebook
6        black            cat          gl
7         bowl      celebrity         goo
8    challenge      christmas      google
9    christmas         comedy        http
10  commercial            diy       https
11         day            dog   instagram
12        espn          ellen       jimmy
13          ft  entertainment        late
14        game           food        like
15          hd          funny        list
16  highlights           game        live
17       house      interview        love
18       james         iphone          ly
19        jedi          james        make
20        john           late       music
21        life           life         nbc
22        like           live         new
23        live           make        news
24        look         makeup   nfacebook
25        love          movie         nfl
26        make         movies     nfollow
27      makeup          music        nget
28         man            nbc       nhttp
29       movie            new      nhttps
30       music           news          ni
31     netflix          night       night
32         new       official  ninstagram
33        news            pop       nlike
34         nfl         review  nsubscribe
35    official        science        nthe
36      review         season    ntwitter
37      season             sp      nwatch
38        star           star    smarturl
39       super          super   subscribe
40        talk           talk        time
41        time        trailer      tumblr
42     trailer          trump     twitter
43       trump       tutorial       video
44       video             tv      videos
45          vs          video       watch
46        wars         videos       world
47        week           wars         www
48       world          world       youtu
49        year        youtube     youtube